app/flaskapp/__init__.py
from instance.config import *
from views import *
from flask import Flask


def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_pyfile('config.py')
    app.register_blueprint(index_page)
    if test_config is None:
        pass
    else:
        pass
    return app


if __name__ == '__main__':
    app = create_app()
    app.run()

app/flaskapp/views.py
from flask import Blueprint, render_template, abort
from jinja2 import TemplateNotFound

index_page = Blueprint('index_page', __name__, template_folder='templates')


@index_page.route('/', defaults={'page': 'index'})
@index_page.route('/<page>')
def show(page):
    try:
        return render_template(f'{page}.html')
    except TemplateNotFound:
        return render_template(f'404.html')

app/flaskapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
            <meta name="description" content="" />
            <meta name="author" content="" />
        {% block title %}
            <title>Bare - Start Bootstrap Template</title>
        {% endblock %}
            <link rel="icon" type="image/x-icon" href="{{ url_for('static',filename='img/favicon.ico') }}"/>
            <link href="{{ url_for('static',filename='css/styles.css') }}" rel="stylesheet" />
            <link href="{{ url_for('static',filename='css/custom.css') }}" rel="stylesheet" />
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        {% endblock %}
    </head>
    <body>
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock %}
        {% block content %}
            <!-- Page content-->
        {% endblock %}
        {% block footer %}
            {% include 'footer.html' %}
        {% endblock %}
        {% block scripts %}
            <script src="{{ url_for('static',filename='js/scripts.js') }}"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        {% endblock %}
    </body>
</html>

app/flaskapp/templates/footer.html
<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

app/flaskapp/templates/index.html
{% extends "base.html" %}
{% block content %}
    {{ super() }}
    <div class="container">
        <div class="text-center mt-5">
            <h1>A Bootstrap 5 Starter Template</h1>
                <p class="lead">A complete project boilerplate built with Bootstrap</p>
                <p>Bootstrap v5.1.0</p>
        </div>
    </div>
{% endblock %}

app/flaskapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('index_page.show') }}">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Link</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>